# Generated by Django 4.2 on 2023-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('login', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=30)),
                ('senha_rep', models.CharField(max_length=50)),
            ],
        ),
    ]
