# Generated by Django 4.2 on 2023-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancousuarios',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
