# Generated by Django 3.2.18 on 2023-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[(0, 'Aluguel'), (1, 'Condomínio'), (2, 'Conta de água'), (3, 'Conta de luz'), (4, 'Gás'), (5, 'Telefone'), (6, 'Internet'), (7, 'IPTU'), (8, 'Financiamento'), (9, 'Outros - casa'), (10, 'Restaurantes'), (11, 'Bar'), (12, 'Cinema'), (13, 'Viagem'), (14, 'Festas/Eventos'), (15, 'Presentes'), (16, 'Outros - Entretenimento'), (17, 'Remédios'), (18, 'Convênio'), (19, 'Outros - Saúde'), (20, 'IPVA'), (21, 'Combustível'), (22, 'Manutenção'), (23, 'Táxi'), (24, 'Transporte público'), (25, 'Outros - Transporte'), (26, 'Comida'), (27, 'Bebida'), (28, 'Produtos de limpeza'), (29, 'Higiene pessoal'), (30, 'Outros - Necessidade'), (31, 'Roupa'), (32, 'Maquiagem'), (33, 'Cosméticos'), (34, 'Outros - pessoal'), (35, 'Cartão'), (36, 'Gastos Pessoais'), (37, 'Investimento PMS'), (38, 'Investimento PMR'), (39, 'Investimento PI'), (40, 'Escola'), (41, 'Roupa - Filho'), (42, 'Brinquedo')], max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('extra_gasto', models.CharField(choices=[('E', 'Extra'), ('G', 'Gasto')], max_length=100)),
                ('data', models.DateField(default='1900-1-2')),
            ],
        ),
    ]
