# Generated by Django 3.2.18 on 2023-04-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contausuario',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='extra_gasto',
            field=models.CharField(max_length=100),
        ),
    ]
