# Generated by Django 3.2.18 on 2023-04-19 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_auto_20230419_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contausuario',
            name='categoria',
            field=models.CharField(blank=True, choices=[(0, 'Aluguel'), (1, 'Condomínio'), (2, 'Conta de água'), (3, 'Conta de luz'), (4, 'Gás'), (5, 'Telefone'), (6, 'Internet'), (7, 'IPTU'), (8, 'Financiamento'), (9, 'Outros - casa'), (10, 'Restaurantes'), (11, 'Bar'), (12, 'Cinema'), (13, 'Viagem'), (14, 'Festas/Eventos'), (15, 'Presentes'), (16, 'Outros - Entretenimento'), (17, 'Remédios'), (18, 'Convênio'), (19, 'Outros - Saúde'), (20, 'IPVA'), (21, 'Combustível'), (22, 'Manutenção'), (23, 'Táxi'), (24, 'Transporte público'), (25, 'Outros - Transporte'), (26, 'Comida'), (27, 'Bebida'), (28, 'Produtos de limpeza'), (29, 'Higiene pessoal'), (30, 'Outros - Necessidade'), (31, 'Roupa'), (32, 'Maquiagem'), (33, 'Cosméticos'), (34, 'Outros - pessoal'), (35, 'Cartão'), (36, 'Gastos Pessoais'), (37, 'Investimento PMS'), (38, 'Investimento PMR'), (39, 'Investimento PI'), (40, 'Escola'), (41, 'Roupa - Filho'), (42, 'Brinquedo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 13, 27, 20, 324638)),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='extra_gasto',
            field=models.CharField(choices=[('G', 'Gasto'), ('E', 'Renda Extra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='login',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
