# Generated by Django 3.2.18 on 2023-04-19 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_auto_20230419_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contausuario',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 13, 33, 37, 837902)),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='extra_gasto',
            field=models.CharField(max_length=100),
        ),
    ]
