# Generated by Django 3.2.18 on 2023-04-19 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0004_auto_20230419_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contausuario',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 13, 44, 11, 753005)),
        ),
    ]
