# Generated by Django 3.2.18 on 2023-04-19 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0005_auto_20230419_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contausuario',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 13, 45, 55, 423060)),
        ),
    ]
