# Generated by Django 3.2.18 on 2023-04-19 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0006_alter_contausuario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contausuario',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 19, 13, 51, 23, 525689)),
        ),
        migrations.AlterField(
            model_name='contausuario',
            name='extra_gasto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
